name: PR Checklist Validation

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Description for Unchecked Checkboxes
      id: checkboxes
      run: |
        # PR 설명 가져오기
        pr_body=$(jq -r .pull_request.body < "$GITHUB_EVENT_PATH")

        # 체크되지 않은 체크박스 검색
        unchecked_count=$(echo "$pr_body" | grep -o '\- \[ \]' | wc -l)

        # echo "UNCHECKED_COUNT=$unchecked_count" >> "$GITHUB_OUTPUT"

        # 체크되지 않은 체크박스가 있다면 오류 발생
        if [ "$unchecked_count" -gt 0 ]; then
          echo "::error title=Unchecked List::There are $unchecked_count unchecked checkboxes in the PR description."
        fi

    # - name: Set status
    #   env:
    #     UNCHECKED_COUNT: ${{ steps.checkboxes.outputs.UNCHECKED_COUNT }}
    #   if: ${{ failure() }}
    #   run: |
    #     echo "아직 확인되지 않은 Checklist 가 $UNCHECKED_COUNT 개 있습니다." >> $GITHUB_STEP_SUMMARY"

